display_name="Ice Beam Moveset"
description="""
Inspired by PM's Ice Beam, this gives samus an overhaul by giving her Ice Beam. Press down special to switch beams, and this will change her Neutral Special, Side Special, Down Tilt, Forward Smash, Forward Air, and Up Throw. She now has a crawl, and a unique crawl attack that can spawn a bomb.
Requires Latest Smashline and Skyline
"""
version="1.0"
category="Param"
authors="C#"